name: Deploy BotDieta

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Acessar servidor via SSH e atualizar o projeto
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "🚀 Conectado ao servidor!"
            
            # Acessar o diretório do projeto
            cd /home/***/dieta30dias/botdieta || exit 1
            
            # Atualizar o repositório
            git config --global --add safe.directory /home/***/dieta30dias/botdieta
            git pull origin main
            
            # Instalar dependências
            npm install
            
            # Parar processo antigo
            pkill -f "node bot.js" || echo "Nenhum processo antigo encontrado."
            
            # Iniciar novo processo em segundo plano
            nohup node dietaBot.js & echo $! 
            
            echo "✅ Deploy concluído com sucesso!"
