name: Deploy BotDieta

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Acessar servidor via SSH e atualizar o projeto
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "🚀 Conectado ao servidor!"
            
            # Acessar o diretório do projeto
            cd /home/***/dieta30dias/botdieta || exit 1

            sudo chown -R ec2-user:ec2-user /home/ec2-user/dieta30dias/botdieta
            sudo chmod -R 755 /home/ec2-user/dieta30dias/botdieta/.git
            sudo chown -R ec2-user:ec2-user /home/ec2-user/.npm
            npm cache clean --force
            sudo chmod 644 /home/ec2-user/dieta30dias/botdieta/package-lock.json
            git config --global --add safe.directory /home/ec2-user/dieta30dias/botdieta

            
            # Atualizar o repositório
            git pull origin main
            
            # Instalar dependências
            npm install
            
            sudo su
            
            echo "stage 2"
            # Parar processo antigo
            sudo pkill -f "node dietaBot.js" || echo "Nenhum processo antigo encontrado."
            echo "stage 3"
            export BOT_TOKEN=${{ secrets.BOT_TOKEN }}
            
            # Iniciar novo processo em segundo plano
            nohup node dietaBot.js &
            
           
            
            echo "✅ Deploy concluído com sucesso!"
